First working version of cartridge!

diff --git a/.openshift/action_hooks/stop b/.openshift/action_hooks/stop
--- a/.openshift/action_hooks/stop
+++ b/.openshift/action_hooks/stop
@@ -1,9 +1,12 @@
-#!/bin/bash
-# The logic to stop your application should be put in this script.
-cd ${OPENSHIFT_REPO_DIR}
-
-if [[ -f "server.pid" ]]; then
-  cd ${OPENSHIFT_DATA_DIR}mule-standalone-3.3.1/bin
-
-  ./mule stop
+if [[ ! -f ${OPENSHIFT_DATA_DIR}mule-standalone-3.3.1/bin ]]; then
+	echo "Error: couldn't find mule executable at ${OPENSHIFT_DATA_DIR}mule-standalone-3.3.1/bin/mule"
+	exit 1
 fi
+
+echo "Stopping mule application"
+
+cd ${OPENSHIFT_DATA_DIR}mule-standalone-3.3.1/bin
+./mule stop
+
+
+
